local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10

  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}

  static_layer:
    enabled: true
    map_topic: "/map"