base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
  min_vel_y: 0.1
  max_vel_x: 0.3
  min_in_place_vel_theta: 0.4
  max_vel_theta: 1.0

  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 3.0

  holonomic_robot: true