#Configuration for EKF localization node

frequency: 10
two_d_mode: true
publish_tf: false

# Coordinate frame specification
odom_frame: odom
base_link_frame: base_link
#world_frame: odom
#map_frame: map

# The odom0 configuration
odom0: /diff_drive_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true,  true,  false,
               false, false, true,
               false, false, false,]
odom0_differential: false

# The imu0 configuration
imu0: /imu
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              true,  false, false,]
imu0_differential: false